### ISSUE TITLE
Does scorpiusjs:bootstrap load only in admin or in the whole site?

### ISSUE THREAD

**Issue by krishaamer** [scorpiusjs/scorpius#13]
If it's still loading in the whole site like in Orion, would make sense to limit it to admin only so one could use Semantic:UI, any other UI package or even no package at all.

Thanks,
Kris

**Comment by romans127** [comment]
Hi Kris.

Add the admin only package for bootstap along side the bootstrap package
and it will stay in admin.

You have to add both because the template declaration is currently written
in the bootstrap package and is replaced with the admin only version in the
admin only package.  This will be updated in the future to always assume
admin only.  And let the user determine the framework.

**Comment by krishaamer** [comment]
Hi Ryan, when you say "admin only package for bootstap" do you mean "nicolaslopezj:orion-admin-only-bootstrap" ?

I started with a fresh scorpius project w/o the compatibility package (which didn't work for me). So now when I try adding nicolaslopezj:orion-admin-only-bootstrap it also loads orion packages which crash the site with

`"Error: A field called name already exists! W20160901-13:22:47.645(3)? (STDERR)     at [object Object].AT.addField (packages/useraccounts_core/lib/core.js:405:1).`

**Comment by romans127** [comment]
That package was ported to scorpius core and reworked a little.

**Comment by romans127** [comment]
Let me know how things go.

**Comment by krishaamer** [comment]
I ended up using the scorpiusjs:materialize-admin-only package instead.

**Comment by romans127** [comment]
Awesome !.
